### ISSUE TITLE
Project Name is trademarked

### ISSUE THREAD

**Issue by danielzev** [ChangeUs/cloudfolio#17]
Hey guys, can you explain why this project is named "portfolium"?

This is a trademarked name for this company: https://portfolium.com/

Let me know, thanks

**Comment by HyeonseoNam** [comment]
Hi, danielzev.
We named it "portfolium" to give a noun feeling on portfolio.
We did not know the existence of this trademark and we will change this project's name soon.
Thanks :)

**Comment by danielzev** [comment]
Thanks for understanding

**Comment by danielzev** [comment]
thanks guys
